trigger:
  - main

pool:
  name: 'Default'
  demands:
    - agent.name -equals MAZI

variables:
  NODE_VERSION: '18.x'
  AZURE_SUBSCRIPTION: 'mern-ecommerce application'
  BACKEND_APP_NAME: 'mern-ecommerce-backend'
  FRONTEND_APP_NAME: 'mern-ecommerce-frontend'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
    displayName: "Use Node.js $(NODE_VERSION)"

  - script: node --version
    displayName: "Check Node.js version"

  # Backend build
  - script: |
      cd server
      npm install
    displayName: "Install Backend Dependencies"

  # Frontend build
  - script: |
      cd client
      npm install
      npm run build
    displayName: "Build Frontend App"

  # Create backend package
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'server'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
    displayName: "Package Backend"

  # Create frontend package
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'client/build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'
    displayName: "Package Frontend"

  # Deploy Backend
  - task: AzureWebApp@1
    inputs:
      azureSubscription: '$(AZURE_SUBSCRIPTION)'
      appName: '$(BACKEND_APP_NAME)'
      package: '$(Build.ArtifactStagingDirectory)/backend.zip'
    displayName: "Deploy Backend to Azure"

  # Deploy Frontend
  - task: AzureWebApp@1
    inputs:
      azureSubscription: '$(AZURE_SUBSCRIPTION)'
      appName: '$(FRONTEND_APP_NAME)'
      package: '$(Build.ArtifactStagingDirectory)/frontend.zip'
    displayName: "Deploy Frontend to Azure"